// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameYkYycfb = "yk_yycfb"

// YkYycfb mapped from table <yk_yycfb>
type YkYycfb struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string `gorm:"column:name" json:"name"`
	Reliang      int32  `gorm:"column:reliang" json:"reliang"`
	Danbai       int32  `gorm:"column:danbai" json:"danbai"`
	Zhifang      int32  `gorm:"column:zhifang" json:"zhifang"`
	Tanshui      int32  `gorm:"column:tanshui" json:"tanshui"`
	Xianwei      int32  `gorm:"column:xianwei" json:"xianwei"`
	Va           int32  `gorm:"column:va" json:"va"`
	Huluobosu    int32  `gorm:"column:huluobosu" json:"huluobosu"`
	Shihuangchun int32  `gorm:"column:shihuangchun" json:"shihuangchun"`
	Liuansu      int32  `gorm:"column:liuansu" json:"liuansu"`
	Hehuangsu    int32  `gorm:"column:hehuangsu" json:"hehuangsu"`
	Yansuan      int32  `gorm:"column:yansuan" json:"yansuan"`
	Vc           int32  `gorm:"column:vc" json:"vc"`
	Ve           int32  `gorm:"column:ve" json:"ve"`
	Danguchun    int32  `gorm:"column:danguchun" json:"danguchun"`
	Jia          int32  `gorm:"column:jia" json:"jia"`
	Na           int32  `gorm:"column:na" json:"na"`
	Gai          int32  `gorm:"column:gai" json:"gai"`
	Mei          int32  `gorm:"column:mei" json:"mei"`
	Tie          int32  `gorm:"column:tie" json:"tie"`
	Meng         int32  `gorm:"column:meng" json:"meng"`
	Xin          int32  `gorm:"column:xin" json:"xin"`
	Tong         int32  `gorm:"column:tong" json:"tong"`
	Lin          int32  `gorm:"column:lin" json:"lin"`
	Xi           int32  `gorm:"column:xi" json:"xi"`
}

// TableName YkYycfb's table name
func (*YkYycfb) TableName() string {
	return TableNameYkYycfb
}
